### PR TITLE
Update udocker to version 1.3.4

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
Hi Mike,

If you have the time, could you please verify:
```
# go to specific working dir
cd /path/to/working-dir

# get 'run.sh' from 'udocker-1.3.3' branch
curl -O https://raw.githubusercontent.com/AMIGA-IAA/hcg-16/udocker-1.3.3/run.sh

# replace all 'hcg-16/master' with 'hcg-16/udocker-1.3.3' in run.sh
sed -i 's/hcg-16\/master/hcg-16\/udocker-1.3.3/g' run.sh

# test it
bash run.sh
```

Feel free to merge if you are happy with the results.

Best regards,
Sebastian

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
`udocker` is going to be added as a `conda-forge` package. Please wait until I confirm so you can test that instead.

**Comment by sebastian-luna-valero** [comment]
Hi Mike,

Please try out this branch and let me know your thoughts.

Best regards,
Sebastian

**Comment by sebastian-luna-valero** [comment]
xref: https://mybinder.readthedocs.io/en/latest/tutorials/reproducibility.html

**Comment by sebastian-luna-valero** [comment]
xref: https://discourse.jupyter.org/t/mamba-env-update-instead-of-mamba-env-create/

**Comment by sebastian-luna-valero** [comment]
xref: https://gist.github.com/bollwyvl/084ee1b86615ee8842b9988d100142eb

**Comment by sebastian-luna-valero** [comment]
@jonesmg incidentally I had to rerun this repo on mybinder and found problems (links above with the details).

Long story short: if we want to keep binder working we need to rename `environment.yml` to something else, and update the references to it accordingly.

I have changed `environment.yml`, would you have time to check whether the workflow has any issues with this new dependencies? There is no rush, so no worries.

Could you please let me know your thoughts?

Best regards,
Sebastian

**Comment by jonesmg** [comment]
Hi Sebastian. Sorry I haven't got to this yet. I've been very busy with other things. I'll try to get to this soon and let you know if I find any issues in the main pipeline. I'm happy for environment yml file to be renamed as needed and I can hunt down the references to it. There shouldn't be many. Cheers, Mike.

**Comment by sebastian-luna-valero** [comment]
Thanks, Mike!

I have already renamed what I think is required, but please double check and test with:

```bash
# go to specific working dir
cd /path/to/working-dir

# get 'run.sh' from 'udocker-1.3.3' branch
curl -O https://raw.githubusercontent.com/AMIGA-IAA/hcg-16/udocker-1.3.3/run.sh

# replace all 'hcg-16/master' with 'hcg-16/udocker-1.3.3' in run.sh
sed -i 's/hcg-16\/master/hcg-16\/udocker-1.3.3/g' run.sh

# test it
bash run.sh
```

**Comment by jonesmg** [comment]
Ok I just check the output from re-running the pipeline and it all looks good. Thanks Sebastian.

**Pull request merged**
